// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfnmvyphsdcyrrdtkaqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indmbm12eXBoc2RjeXJyZHRrYXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzU0NzksImV4cCI6MjA1ODkxMTQ3OX0.TtIugogKKRxs7krnCE4TJTTcDPGK_1cHpG-LjY6nH2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);